# Generated by Django 5.2.8 on 2025-11-08 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={},
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='producttag',
            name='created_at',
        ),
    ]
