# Generated by Django 5.2.8 on 2025-11-09 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_category_options_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-stocked_at']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='stocked_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
