# Generated by Django 5.2.8 on 2025-11-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
